### ISSUE TITLE
Provide JSON and/or CSV output of talks

### ISSUE THREAD

**Issue by BigLep** [ipfs-shipyard/ipfs-thing-2022#108]
## Done Criteria
It's self-service for a non-developer to quickly get a dump of all the talks in an easy-to-use form like JSON and/or CSV.  

## Why Important
Tabular data is easy for non-developers to sort, filter, etc. due to the good GUI tools available (e.g., spreadsheets, Notion).  Getting our talk data into that form would make it more self-service for event organizers to:
1. Create a table of talks with links to output like slides, recording, and notes.
2. See which talks a given person is giving in case there are any conflicts
3. etc.
 
## Notes
A readme comment on how to get TOML → CSV was added here: https://github.com/ipfs-shipyard/ipfs-thing-2022/pull/99 .  Ideally though as part of the build step we'd just generate a CSV and/or JSON dump that can be accessed statically by anyone without needing to install 3rd party tools or run extra commands.

It looks like we just need to call ``loadEvents`` in https://github.com/ipfs-shipyard/ipfs-thing-2022/blob/main/website/lib/data.js and then dump the output.

Ideally this would be upstreamed into https://github.com/jbenet/devent-website , but I don't have access to the repo to create the issue.  We can get it working here and then upstream.

**Comment by BigLep** [comment]
@SgtPooki: do you think you could take this on?

**Comment by SgtPooki** [comment]
@BigLep absolutely. I should be able to get a PR out before EOD
