### ISSUE TITLE
Augment website with talk notes and output

### ISSUE THREAD

**Issue by BigLep** [ipfs-shipyard/ipfs-thing-2022#110]
## Background and problem
In my opinion, the IPFS Thing website is great for:
1. Official/polished communication and branding.  It brings a sense of "legitimacy" to the event.
2. Good balance between collaboration and review/control with the GitHub PR flow for organizing tracks and talks.  It's self-service for someone to propose a track/talk but there also gates in place to help make sure it "fits".

I don't think the site is great for quick edits for capturing things like discussion notes or links to other resources (slides, videos, etc.).  If there is friction of needing to get PRs merged to get this stuff in, it's going to prevent participants from doing it.  I want to remove as much friction as possible.

As a result, I'd propose we have another place that allows quicker self-service note/output capturing per talk.  We can always add a pointer to these per-talk "pages".  

## Requirements
1. "easy" editing to capture notes, URLs, outputs from a talk
2. self-service to adjust as new talks are added.  One shouldn't need to rely on anyone else to spin this up.

### Notion
Pros:
* Collaborative editing
* Simple to use
* Can have structured data

Cons:
* Proprietary SaaS platform
* Instance "owned" by one company (e.g., PL EngRes, Number0)
* If don't have an account already, it's another proprietary thing that someone eventually has to pay for.

### IPFS Discourse
Pros:
* Not branded toward a single company
* Open Source product
* It's where we ask the community to discuss anyway thus naturally gives higher visibility to the community
* Much of the community already has accounts for it, and if they don't it's self-service to get one.

Cons:
* Not going to get a quick table export of all the sessions with some structured data (e.g., links to slides, videos).  The biggest value I see in structured data is for catching the cases where we're missing things like slides, videos.
* Doesn't have collaborative editing for notetaking during a session.  It won't be transparent what others have typed/captured until they submit.  This can lead to duplication or cause folks to assume that someone else is taking care of it.
* To make it easily navigatable, I think we'll need to create one post per talk.  I don't know if there's a way to do a bulk import of posts from a CSV file.

### GitHub
Similar to IPFS Discourse.

Additional Pros:
* Everyone has an account.
* Surely possible to easily precreate a bunch of issues or "talk files" that PRs get created against

Additional Cons:
* If PRs are involved, there are extra steps for getting content merged.

## Recommendation
Lean into IPFS Discourse.  To pull this off, I would:
1. Create an [IPFS Thing category](https://discuss.ipfs.io/c/domain-specific-and-location-specific-communities/ipfs-thing-2022/32)
2. Create a post for each track ([example where this had already been done](https://discuss.ipfs.io/t/building-apps-on-ipfs-track/14605))
3. For each .toml track in https://github.com/ipfs-shipyard/ipfs-thing-2022/tree/main/events, set the "website" to the discuss.ipfs.io post.
4. Communicate expectations of track leads and participants to use Discourse for capturing track links and outputs.

We unfortunately don't get collaborative editing, but it's self-service for anyone to make posts and replies through the event as things evolve.

**Comment by bmann** [comment]
Discourse can enable “wiki” editing. It’s not real time collaborative but it can be made to edit by anyone. 

And thanks for channeling exactly what I was thinking ;)

I still need to change the link for my track.

**Comment by BigLep** [comment]
PR to add IPFS Discourse "website" links for each track: https://github.com/ipfs-shipyard/ipfs-thing-2022/pull/118

**Comment by jbenet** [comment]
- yeah, this website is not meant to capture notes or outputs -- let's definitely do that elsewhere
- thanks for generating discourse pages and PRing in -- It's great to have a good default
- i think various people will find different platforms more or less effective for them. I don't think forcing one thing is viable or optimal. track leads (or even the session speaker/facilitator/lead) should have a default, but ultimately decide what's best for them.

**Comment by SgtPooki** [comment]
@BigLep is #118 enough to close this out or do we need more done to close this out?

**Comment by BigLep** [comment]
Yeah, I think we're good to close this out.  Doing so now...
