### ISSUE TITLE
need to be able to link to a track

### ISSUE THREAD

**Issue by jbenet** [ipfs-shipyard/ipfs-thing-2022#125]
- need to be able to link to a track
- should auto-open the modal
- url should change when clicking an event (& opening a modal) to allow easy copy pasting
- easiest:  `<url>#<event-filename>` (eg `<url>#c_1_data_and_ipfs-1`)
- nicer: `<url>#<event-name-slug>` (eg `<url>#data-and-ipfs-mobile`)

**Comment by SgtPooki** [comment]
working on this now
