### ISSUE TITLE
Ideas for Project and Community track

### ISSUE THREAD

**Issue by mishmosh** [ipfs-shipyard/ipfs-thing-2022#22]
There are currently 4 sessions planned for the Project and Community track. Have other ideas? Please suggest via comments on this issue, or via a PR to https://github.com/ipfs-shipyard/ipfs-thing-2022/blob/main/events/c_3_project_and_community.toml

**Comment by BigLep** [comment]
I'll contribute some more idea here tomorrow (2022-06-17).

**Comment by BigLep** [comment]
I got waylaid with a security event on Friday.  This is on my list for 2022-06-20.

**Comment by BigLep** [comment]
> @BigLep Apologies, I must have missed the notifications on this.

All good - no problem.

> 1-2. I am OOO next week and it seems like we're running out of time to prep these things. Would you be down to set aside some afternoon hack time for them, though?

EngRes IPFS Stewards will do an hour working session on this before the event during the week of 2022-07-04.  I'm game to have a followup session in Iceland as well.

> 3-4. Great! Do you think "a month in" could be done in 15 mins? Do you have a presenter in mind for #4? I am hearing from @b5 that there may be additional submissions to this track, so I may extend this track length. Would you be available in the afternoon too?

I can cover 3 and 4.  I can cram things into 15 minutes and/or can do things in the afternoon as well.  I'll get a PR for this today or next week.

> 5. Do you think this might fit better in the "Measuring IPFS" track led by @yiannisbot? Or are you talking about project & community metrics (in the vein of orbit.love)?

I was thinking more about community metrics and project metrics.  Basically, what does it look like for the IPFS ecosystem to be thriving?  # of nodes is one measure, but also things like how many are contributing to codebases, how many active implementations are being developed, etc.

> 6. Already merged!

Great, thanks.

> 7. Yes, I think this fits better in the implementations track.

Great, we'll get them added there.
