### ISSUE TITLE
Move Identity and AC to Friday

### ISSUE THREAD

**Issue by oed** [ipfs-shipyard/ipfs-thing-2022#26]
Excited for the event, thanks for putting this on!

Coincidentally I was already going to Reykjavik for a family trip this week 😄  
Friday is the only day I can really participate in full and I would love to be fully part of the **Identity & Access Control** track. Have a few things and learnings I could share from my work on Ceramic there. 

Would it be possible to move the **Identity & Access Control** to Friday?

**Comment by oed** [comment]
Interested yes :) Can you tell me more about what the responsibilities of leading a track would entail?

**Comment by b5** [comment]
Apologies for the slow response here. As you may have seen @oed, this track has been renamed to `Building Apps on IPFS`, and is not being lead by @bmann. Unfortunately we'll be keeping the track on Monday.

I'm going to close this, but would be happy to chat on Discord about your plan to participate 😄

**Comment by b5** [comment]
Follow ups:

* If you have a talk about ceramic you'd like to give, but can only be there on Friday, let me know. We might be able to arrange a room for you to give your talk & get it onto YouTube
* We also have the hack space! If you're only in on Friday we could make a point of letting folks know you're around to chat about ceramic

**Comment by oed** [comment]
Thanks for the update @b5 Mohsin from our team is giving a talk on the *Building apps* track: https://github.com/ipfs-shipyard/ipfs-thing-2022/pull/80

I might also submit something for friday.
