### ISSUE TITLE
Interest in an 'IPFS in Browsers' talk/workshop/session?

### ISSUE THREAD

**Issue by ikreymer** [ipfs-shipyard/ipfs-thing-2022#31]
I'd be interested in attending and perhaps being part of a focused 'IPFS in Browsers' discussion/workshop, talking about all the things related to making IPFS read and write access feasible in browsers, covering the gamut of access and usage patterns/apis via gateways, js-ipfs, js-ipfs-fetch, IPFS Companion, extensions vs regular pages, services like web3.storage, native support in Brave, Agregore, mobile, etc...
(Perhaps working out some of the issues @RangerMauve has begun to summarize here webrecorder/archiveweb.page#85)

Wanted to gauge interest before opening a PR @lidel @autonome @RangerMauve

**Comment by RangerMauve** [comment]
Yeah, I'd love to have a segment to talk about protocol handlers and the stuff I've been doing with `ipfs/ipns/pubsub` in Agregore. 😁

**Comment by b5** [comment]
fantastic suggestion. How would y'all feel about these changes:

* Rename "Lite clients" track to "Browsers and Mobile"
* Invite @achingbrain to attend so we have js-ipfs representation
* Invite Fission folks (cc @matheus23, @bmann) - they're deep into the IPFS-in-browser use case

I'm going to open a PR that makes these changes to see if the schedule works out, and provide rationale as to why I think there are all examples of the same "lite client" problem.

**Comment by BigLep** [comment]
A couple of areas that I think would be useful to have here:
1. Plans/roadmap for js-ipfs.  This would be @achingbrain .
2. Browser connectivity overview.  @marten-seemann would be a good candidate to cover this giving the overview of what you get and don't get (in terms of barrier to entry, performance, browser market penetraction, etc.) with web sockets, webrtc, and webtransport.  It could also be a good forum for any demos (e.g., browser nodes talking with the rest of the IPFS network over WebTransport.

**Comment by ikreymer** [comment]
From the perspective of someone wishing to use 'IPFS in Browsers', I think this topic could further be thought of as these distinct but overlapping areas:

1) js-ipfs capabilities in today's most popular browsers (chrome/firefox/safari) (sort of what @BigLep mentioned above)
2) IPFS over HTTP APIs for both read and write/pin, HTTP gateways, web3.storage, fission.codes services, other tools and services that interface with IPFS.
3) IPFS in browsers that provide access to a native IPFS node with pinning, and perhaps also custom protocol handlers, etc.. (currently Brave, Agregore, maybe more?)
